### ISSUE TITLE
andriod-LiteAVSDK_Player_6.7.7734-同一个视频，有的手机可以播放，有的手机播放不了

### ISSUE THREAD

**Issue by StarAndRainbow** [tencentyun/SuperPlayer_Android#115]
【Android】-【6.7.7734】：【小米8se播放视频提示SuperPlayerView: onFail: errorCode = -1 message = http request error.】
【集成包】：LiteAVSDK_Player_6.7.7734
【当前现象】：旧版LiteAVSDK_Player_6.7.7734升级到新版sdk7.5.9307,发布之后，很多用户反馈有的视频播放不了。经过测试发现，同一个视频有的手机可播放，有的手机不可播放。回退到旧版本LiteAVSDK_Player_6.7.7734，测试也发现这个问题，同一个视频，使用LiteAVSDK_Player_6.7.7734，华为note1可以播放，小米8se播放不了。使用LiteAVSDK_Player_7.5.9307，和之前播放同一个视频，小米8se可以播放，华为note1播放不了。项目中的绝大多数视频都是可以正常播放的
【之前版本有无此问题】：LiteAVSDK_Player_6.7.7734有此问题，LiteAVSDK_Player_7.5.9307也有此问题，同一个视频有的手机可以播放，有的视频不可以播放
【有无日志或者截图】：下面是LiteAVSDK_Player_6.7.7734的日志
由于职位太低，拿不到腾讯云的账号登录提工单，只能github提bug了，为什么有的手机会报errorCode = -1 message = http request error.

日志

    响应数据------{
    	"code":200,
    	"data":{
    		"appID":"1257402134",
    		"fileID":"5285890794276280516",
    		"sign":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cmxBY2Nlc3NJbmZvIjp7InQiOiI1ZjU2MGRjMCJ9LCJhcHBJZCI6MTI1NzQwMjEzNCwiZXhwaXJlVGltZVN0YW1wIjoxNTk5NDc1MTM2LCJjdXJyZW50VGltZVN0YW1wIjoxNTk5Mzg4NzM2LCJmaWxlSWQiOiI1Mjg1ODkwNzk0Mjc2MjgwNTE2In0.zcbLQd0cxgCgFSwFf_D4z5HRKxaZCQhz0274HYMmx_s",
    		"timeout":"5f560dc0"
    	},
    	"message":"成功"
    } 请求用时--------95.6ms
    Server: nginx/1.16.1
    Date: Mon, 07 Sep 2020 02:11:21 GMT
    Content-Type: application/json;charset=utf-8
    Content-Length: 416
    Connection: keep-alive
    Cache-Control: 
2020-09-07 10:11:21.167 30317-30317/com.qunyu.dividedroad I/hpplay-java: [main]:LelinkCastPlayer:getConnectLelinkServiceInfos
2020-09-07 10:11:21.168 30317-30317/com.qunyu.dividedroad E/SuperPlayerView: stopPlay mCurrentPlayState:2
2020-09-07 10:11:21.170 30317-30317/com.qunyu.dividedroad I/SuperVodInfoLoaderV3: getVodByFileId: url = http://playvideo.qcloud.com/getplayinfo/v2/1257402134/5285890794276280516?t=5f560dc0&sign=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cmxBY2Nlc3NJbmZvIjp7InQiOiI1ZjU2MGRjMCJ9LCJhcHBJZCI6MTI1NzQwMjEzNCwiZXhwaXJlVGltZVN0YW1wIjoxNTk5NDc1MTM2LCJjdXJyZW50VGltZVN0YW1wIjoxNTk5Mzg4NzM2LCJmaWxlSWQiOiI1Mjg1ODkwNzk0Mjc2MjgwNTE2In0.zcbLQd0cxgCgFSwFf_D4z5HRKxaZCQhz0274HYMmx_s
2020-09-07 10:11:21.170 30317-30317/com.qunyu.dividedroad W/video render: timetrack start play
2020-09-07 10:11:22.345 30317-31504/com.qunyu.dividedroad W/System.err: java.io.FileNotFoundException: http://playvideo.qcloud.com/getplayinfo/v2/1257402134/5285890794276280516?t=5f560dc0&sign=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cmxBY2Nlc3NJbmZvIjp7InQiOiI1ZjU2MGRjMCJ9LCJhcHBJZCI6MTI1NzQwMjEzNCwiZXhwaXJlVGltZVN0YW1wIjoxNTk5NDc1MTM2LCJjdXJyZW50VGltZVN0YW1wIjoxNTk5Mzg4NzM2LCJmaWxlSWQiOiI1Mjg1ODkwNzk0Mjc2MjgwNTE2In0.zcbLQd0cxgCgFSwFf_D4z5HRKxaZCQhz0274HYMmx_s
2020-09-07 10:11:22.345 30317-31504/com.qunyu.dividedroad W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
2020-09-07 10:11:22.345 30317-31504/com.qunyu.dividedroad W/System.err:     at com.tencent.liteav.demo.play.net.TCHttpURLClient$1.run(TCHttpURLClient.java:56)
2020-09-07 10:11:22.346 30317-31504/com.qunyu.dividedroad W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2020-09-07 10:11:22.346 30317-31504/com.qunyu.dividedroad W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-09-07 10:11:22.346 30317-31504/com.qunyu.dividedroad W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-09-07 10:11:22.346 30317-31504/com.qunyu.dividedroad W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-09-07 10:11:22.350 30317-30317/com.qunyu.dividedroad I/SuperPlayerView: onFail: errorCode = -1 message = http request error.
2020-09-07 10:11:22.404 30317-30317/com.qunyu.dividedroad I/Toast: Show toast from OpPackageName:com.qunyu.dividedroad, PackageName:com.qunyu.dividedroad
2020-09-07 10:11:27.002 30317-31495/com.qunyu.dividedroad D/hpplay-java: [Cyber.ThreadCore]:checkdev:Disposer start : 60000

**Comment by StarAndRainbow** [comment]
补充说明，使用新版的LiteAVSDK_Player_7.5.9307，播放同一个视频有的手机报错提示，code = 1009 msg = token contains an invalid number of segments ,有的手机可以正常播放

**Comment by StarAndRainbow** [comment]
解决了，新旧版本，后台做了一天缓存，新旧版用了不同的加密，打扰了
