### ISSUE TITLE
【Android11】-【7.7.9457】：【Crash】

### ISSUE THREAD

**Issue by jin123d** [tencentyun/SuperPlayer_Android#117]
>* 【Android】-【7.7.9457】：【Crash】
>* 【集成包】：LiteAVSDK_Player_7.7.9457.aar
>* 【当前现象】：play/stop crash
>* 【机型】：Android Virtual Devices R

```
java.lang.reflect.UndeclaredThrowableException
	at $Proxy3.getNetworkTypeForSubscriber(Unknown Source)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2960)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2924)
	at com.tencent.liteav.basic.util.e.c(TXCSystemUtil.java:195)
	at com.tencent.liteav.b.i(TXCDataReport.java:1362)
	at com.tencent.liteav.b.a(TXCDataReport.java:202)
	at com.tencent.liteav.c.r(TXCLivePlayer.java:662)
	at com.tencent.liteav.c.a(TXCLivePlayer.java:266)
	at com.tencent.rtmp.a.a(TXLivePlayerImpl.java:207)
	at com.tencent.rtmp.TXLivePlayer.startPlay(TXLivePlayer.java:114)
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at com.tencent.liteav.b.a(TXCDataReport.java:489)
	at com.tencent.liteav.b.b(TXCDataReport.java:231)
	at com.tencent.liteav.c.s(TXCLivePlayer.java:667)
	at com.tencent.liteav.c.a(TXCLivePlayer.java:317)
	at com.tencent.rtmp.a.a(TXLivePlayerImpl.java:255)
	at com.tencent.rtmp.TXLivePlayer.stopPlay(TXLivePlayer.java:128)
```

**Comment by 284419487** [comment]
SDK不支持虚拟机环境，建议用真机进行测试
