### ISSUE TITLE
TXVodDownloadManager抛ConcurrentModificationException

### ISSUE THREAD

**Issue by dushicai** [tencentyun/SuperPlayer_Android#162]
【Android】-【8.9.10355】：【TXVodDownloadManager抛出异常】
【集成包】：com.tencent.liteav:LiteAVSDK_Professional:8.9.10355
【当前现象】：缓存hls内容报错。这个问题存在过很多版本一直未修复
【机型】：安卓设备
【之前版本有无此问题】：一直有
【日志】：
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.tencent.rtmp.downloader.TXVodDownloadManager.convertMedia(TXVodDownloadManager.java:387)
	at com.tencent.rtmp.downloader.TXVodDownloadManager$2.downloadProgress(TXVodDownloadManager.java:370)
	at com.tencent.ijk.media.player.IjkDownloadCenter$EventHandler.handleMessage(IjkDownloadCenter.java:168)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，这个是下载集成报错的问题，可以提供下具体使用场景，方便进一步定位问题
技术问题 欢迎交流 q2562367495注明来意
