### ISSUE TITLE
TXCLog.init导致卡顿

### ISSUE THREAD

**Issue by hexi** [tencentyun/SuperPlayer_Android#33]
```
at com.tencent.liteav.basic.log.TXCLog.nativeLogOpen(Native Method)
	at com.tencent.liteav.basic.log.TXCLog.init(TXCLog.java:12)
	at com.tencent.rtmp.TXVodPlayer.<init>(TXVodPlayer.java:9)
	at com.tencent.liteav.demo.play.SuperPlayerView.initVodPlayer(SuperPlayerView.java:2)
	at com.tencent.liteav.demo.play.SuperPlayerView.playWithMode(SuperPlayerView.java:7)
	at com.spero.vision.vsnapp.common.comment.M.onClick(VideoCommentFragment.kt:10)
	at android.view.View.performClick(View.java:5212)
	at com.spero.vision.vsnapp.common.comment.VideoCommentFragment.te(VideoCommentFragment.kt:21)
	at com.spero.vision.vsnapp.common.comment.VideoCommentFragment.fe(VideoCommentFragment.kt:13)
	at com.spero.vision.vsnapp.common.comment.VideoCommentFragment.ge(VideoCommentFragment.kt:2)
	at com.spero.vision.vsnapp.common.comment.VideoCommentFragment.onViewCreated(VideoCommentFragment.kt:6)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:72)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:6)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:150)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:2)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:1)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:5)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at com.ytx.appframework.BaseActivity.onStart(BaseActivity.java:1)
	at com.spero.vision.vsnapp.common.comment.VideoCommentActivity.onStart(VideoCommentActivity.kt:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)
	at android.app.Activity.performStart(Activity.java:6326)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2477)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574)
	at android.app.ActivityThread.access$1000(ActivityThread.java:166)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5563)
```

**Comment by AlphaHans** [comment]
请问这里是发生了什么？ ANR了么？ 如果ANR了，麻烦把traces提供一下。
