### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.ijk.media.player.IjkMediaPlayer.native_init

### ISSUE THREAD

**Issue by hexi** [tencentyun/SuperPlayer_Android#43]
# LiteAVSDK_Professional_6.6.7553版本
```
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.ijk.media.player.IjkMediaPlayer.native_init() (tried Java_com_tencent_ijk_media_player_IjkMediaPlayer_native_1init and Java_com_tencent_ijk_media_player_IjkMediaPlayer_native_1init__)
at com.tencent.ijk.media.player.IjkMediaPlayer.native_init(Native Method)
at com.tencent.ijk.media.player.IjkMediaPlayer.initNativeOnce(IjkMediaPlayer.java:3)
at com.tencent.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:2)
at com.tencent.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:4)
at com.tencent.liteav.txcvodplayer.TXCVodVideoView.f(TXCVodVideoView.java:16)
at com.tencent.liteav.txcvodplayer.TXCVodVideoView.w(TXCVodVideoView.java:1)
at com.tencent.liteav.txcvodplayer.TXCVodVideoView$7.a(TXCVodVideoView.java:17)
at com.tencent.liteav.txcvodplayer.TextureRenderView$b.onSurfaceTextureAvailable(TextureRenderView.java:7)
at android.view.TextureView.getHardwareLayer(TextureView.java:450)
at android.view.TextureView.draw(TextureView.java:383)
at android.view.View.updateDisplayListIfDirty(View.java:18403)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.draw(View.java:19456)
at android.view.View.updateDisplayListIfDirty(View.java:18403)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:1)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:32)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.draw(View.java:19456)
at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1)
at android.view.View.updateDisplayListIfDirty(View.java:18403)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:32)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.draw(View.java:19456)
at android.view.View.updateDisplayListIfDirty(View.java:18403)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4087)
at android.view.View.updateDisplayListIfDirty(View.java:18394)
at android.view.View.draw(View.java:19181)
at android.view.ViewGroup.drawChild(ViewGroup.java:4324)

```

**Comment by wzyzb** [comment]
这个问题可能的原因是so没有加载，请问下你的机器是什么型号的？

**Comment by HancockY** [comment]
我也是这个问题 华为荣耀10

**Comment by wzyzb** [comment]
这个问题的原因是so没有加载到，你们看下apk包里面是否有相应so,cpu架构是否正确

**Comment by HancockY** [comment]
> 这个问题的原因是so没有加载到，你们看下apk包里面是否有相应so,cpu架构是否正确

我把jnilibs里面的全部文件复制过来, 然后配置上了abiFilters, 这个问题解决了. 感谢, 不过之前用的7734版本, 只需要LiteAVSDK_Player这个aar加上libsuperplayer这个库就可以了, 这次升级7754才出现这个问题的

**Comment by HancockY** [comment]
又测试了几次, 把jbilibs, abifilters 都删掉, 然后又没有问题了...完全蒙蔽了

**Comment by HancockY** [comment]
没法传图片 描述下现在依赖情况: 只有 LiteAVSDK_Player_6.7.7754的aar, libsuperplayer的module依赖 libsuperplayer中的构建版本和targetVersion版本都和主项目一致:29. 没有jnilibs, 没有abifilter. 正常使用了

**Comment by wzyzb** [comment]
好的，正常就好
