### ISSUE TITLE
jni报错 UnsatisfiedLinkError

### ISSUE THREAD

**Issue by zhw634631** [tencentyun/SuperPlayer_Android#65]
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
	at com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport(Native Method)
	at com.tencent.liteav.basic.datareport.TXCDRApi.<clinit>(:418)
	at com.tencent.liteav.basic.datareport.TXCDRApi.initCrashReport(:397)
	at com.tencent.rtmp.TXVodPlayer.startPlay(:184)
	at com.tencent.liteav.demo.play.SuperPlayerView.playVodURL(:234)
	at com.tencent.liteav.demo.play.SuperPlayerView.playWithModel(:196)
	at com.tinytiger.titi.ui.video.VideoDetailActivity.d(:711)
	at com.tinytiger.titi.ui.video.VideoDetailActivity.F(:720)
	at com.tinytiger.titi.ui.video.VideoDetailActivity.initView(:177)
	at d.o.a.e.a.onCreate(:46)
	at android.app.Activity.performCreate(Activity.java:6262)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5415)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
	at de.robv.android.xp0sed.Xp0sedBridge.main(Xp0sedBridge.java:102)

机型:vivo X9 系统:6.0

**Comment by wzyzb** [comment]
这个是so加载未成功，你看下是否打包了so在apk中

**Comment by zhw634631** [comment]
so包在的,五部测试机就这一部出问题

**Comment by wzyzb** [comment]
检查下是否打包了对应cpu型号的so,apk安装后在对应路径下面是否有so

**Comment by Wi1ls** [comment]
> so包在的,五部测试机就这一部出问题

你好 解决了吗？ 我在vivo x7也有同样的问题

**Comment by Vander-liu** [comment]
@Wi1ls  后来解决了，我这小米8Lite 偶现此问题
