### ISSUE TITLE
把aar替换为最新的版本，播放视频的时候奔溃

### ISSUE THREAD

**Issue by zhangshaobo87** [tencentyun/SuperPlayer_Android#67]
![image](https://user-images.githubusercontent.com/17812840/71758297-ca4bcb80-2ed8-11ea-8c32-551a3b6f61d0.png)
 java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
        at com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport(Native Method)
        at com.tencent.liteav.basic.datareport.TXCDRApi.<clinit>(TXCDRApi.java:418)
        at com.tencent.liteav.basic.datareport.TXCDRApi.initCrashReport(TXCDRApi.java:397)
        at com.tencent.rtmp.TXVodPlayer.startPlay(TXVodPlayer.java:184)
        at com.tencent.liteav.demo.play.SuperPlayerView.playVodURL(SuperPlayerView.java:817)
        at com.tencent.liteav.demo.play.SuperPlayerView.playWithModel(SuperPlayerView.java:674)

**Comment by wzyzb** [comment]
ao加载未成功，检查下app里面是否打包了so
